### ISSUE TITLE
Добавить статусную модель заказа

### ISSUE THREAD

**Issue by Moress** [de1mos242/OrderTable#12]
Управление на владельце заказа.
Примерные статусы и ограничения:
1. Подготовка - можно изменить состав заказа, участников
2. Оплата - фиксация оплат
3. Ушел к исполнителю - ничего менять нельзя.

**Comment by de1mos242** [comment]
Подготовка: Prepare - виден только автору
Сборка: Build - разрешено добавление участников и наполнение позиций
Отправка: Send - разрешены переход к оплатам и возврат к сборке (кто-то не успел или чего-то нет в наличии)
Оплата: Pay - автор (возможно в дальнейшем отдельная роль заказчика) может собирать и отмечать факт оплаты. Разрешено закрытие заказа (даже без полной оплаты) и возврат на этап сборки (факты оплат сохраняются)
Закрыт: Close - разрешен возврат на этап оплат
